export const sharedAccesories = [
	{ name: "Individual Color", price: 8000, id: "addColor" },
	{ name: "Jet button", price: 500, id: "jetBtn" },
	{ name: "Autodestruction button", price: 1000, id: "destrBtn" },
]
export const brandColors = {
	"Dom's": "#f0e3d9",
	DeLorean: "#e5eded",
	Chevrolet: "#e2e7e0",
	Porsche: "#f1ebcd",
}
export const cars = [
	{
		id: 1,
		model: "Dodge Charger",
		brand: "Dom's",
		year: 1970,
		enginePower: "375",
		mileage: "50,000",
		price: 90000,
		image: "./assets/Dom's Dodge Charger.png",
		accessoriesByModel: [
			{ name: "Cameleon effect", price: 1500, id: "cameleon" },
		],
	},
	{
		id: 2,
		model: "DMC-12",
		brand: "DeLorean",
		year: 1981,
		enginePower: "130",
		mileage: "30,000",
		price: 70000,
		image: "./assets/DeLorean DMC-12.png",
		accessoriesByModel: [],
	},
	{
		id: 3,
		model: "Camaro Z28",
		brand: "Chevrolet",
		year: 1969,
		enginePower: "290",
		mileage: "80,000",
		price: 55000,
		image: "./assets/Chevrolet Camaro Z28.png",
		accessoriesByModel: [],
	},
	{
		id: 4,
		model: "911",
		brand: "Porsche",
		year: 2022,
		enginePower: "450",
		mileage: "10,000",
		price: 150000,
		image: "./assets/Porche 911.png",
		accessoriesByModel: [],
	},
	{
		id: 5,
		model: "Corvette",
		brand: "Chevrolet",
		year: 2020,
		enginePower: "490",
		mileage: "15,000",
		price: 85000,
		image: "./assets/Corvette.png",
		accessoriesByModel: [],
	},
]
